name: documentation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install Dependencies and Build
        run: |
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm install
          fi
          yarn build --out-dir build/${{ secrets.PASSWORD }}
  
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      
      - name: Create .env file
        run: |
          echo "WIKI_BASE_URL=${{ secrets.WIKI_BASE_URL }}" >> .env
          cat .env
      
      - name: Install Dependencies and Build
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            yarn install --immutable
          else
            yarn install
          fi
          yarn build --out-dir build/${{ secrets.PASSWORD }}
      
      - name: Copy Locking System
        run: cp -r lockscreen/* build/
      
      - name: Deploy Documents
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          git config --global core.sshCommand 'ssh -i ${{ secrets.GH_PAGES_DEPLOY }} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
          git clone --branch=gh-pages --depth=1 "https://github.com/mohammedfajer/notes.git" gh-pages
          rsync -av --checksum --delete --exclude CNAME --exclude .nojekyll --exclude .ssh --exclude .git --exclude .github build/ gh-pages/
          cd gh-pages
          git add -A
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages
      env:
        GH_PAGES_DEPLOY: ${{ secrets.GH_PAGES_DEPLOY }}